apiVersion: chaos-mesh.org/v1alpha1
kind: DNSChaos
metadata:
  name: openai-dns-failure
  namespace: dev
spec:
  action: error
  mode: all
  selector:
    namespaces:
      - dev
    labelSelectors:
      app: joke-worker
  patterns:
    - "api.openai.com"
    - "*.openai.com"
  duration: "5m" 