apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: redis-memory-stress
  namespace: dev
spec:
  mode: one
  selector:
    namespaces:
      - dev
    labelSelectors:
      app: redis
  stressors:
    memory:
      workers: 1
      size: "256MB"
      options: ["--vm-hang", "30"]  # Hang for 30s after allocating memory
  duration: "5m"
  scheduler:
    cron: "@every 10m"  # Optional: repeat every 10 minutes 