apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  internal.override: |
    internal.k8sdr.com:53 {
        errors
        cache 10 {
            success 10
            denial 10
        }
        forward . /etc/resolv.conf {
            max_concurrent 1000
        }
        reload
        loadbalance
    } 